CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA core;

CREATE EXTENSION IF NOT EXISTS ltree WITH SCHEMA core;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA core;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA core;

CREATE SCHEMA IF NOT EXISTS core;
